services:
  - type: web
    name: gfpgan-api
    env: python
    plan: free
    buildCommand: bash render-build.sh && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
